export const ADMIN_HOTELS_REQUEST = 'ADMIN_HOTELS_REQUEST'
export const ADMIN_HOTELS_SUCCESS = 'ADMIN_HOTELS_SUCCESS'
export const ADMIN_HOTELS_FAIL = 'ADMIN_HOTELS_FAIL'

export const ALL_HOTELS_REQUEST = 'ALL_HOTELS_REQUEST'
export const ALL_HOTELS_SUCCESS = 'ALL_HOTELS_SUCCESS'
export const ALL_HOTELS_FAIL = 'ALL_HOTELS_FAIL'

export const NEW_HOTEL_REQUEST = 'NEW_HOTEL_REQUEST'
export const NEW_HOTEL_SUCCESS = 'NEW_HOTEL_SUCCESS'
export const NEW_HOTEL_RESET = 'NEW_HOTEL_RESET'
export const NEW_HOTEL_FAIL = 'NEW_HOTEL_FAIL'

export const DELETE_HOTEL_REQUEST = 'DELETE_HOTEL_REQUEST'
export const DELETE_HOTEL_SUCCESS = 'DELETE_HOTEL_SUCCESS'
export const DELETE_HOTEL_RESET = 'DELETE_HOTEL_RESET'
export const DELETE_HOTEL_FAIL = 'DELETE_HOTEL_FAIL'

export const UPDATE_HOTEL_REQUEST = 'UPDATE_HOTEL_REQUEST'
export const UPDATE_HOTEL_SUCCESS = 'UPDATE_HOTEL_SUCCESS'
export const UPDATE_HOTEL_RESET = 'UPDATE_HOTEL_RESET'
export const UPDATE_HOTEL_FAIL = 'UPDATE_HOTEL_FAIL'

export const HOTEL_DETAILS_REQUEST = 'HOTEL_DETAILS_REQUEST'
export const HOTEL_DETAILS_SUCCESS = 'HOTEL_DETAILS_SUCCESS'
export const HOTEL_DETAILS_FAIL = 'HOTEL_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const ALL_REVIEWS_REQUEST = 'ALL_REVIEWS_REQUEST'
export const ALL_REVIEWS_SUCCESS = 'ALL_REVIEWS_SUCCESS'
export const ALL_REVIEWS_FAIL = 'ALL_REVIEWS_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'